version: '3.9'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
  validator-endpoint:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: api
    depends_on:
      - redis
    environment:
      HOTKEY_MNEMONIC: "my_validators_secret_mnemonic_phrase_here"





